# Generated by Django 2.1.7 on 2019-03-07 17:44

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190307_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
    ]
